### ISSUE TITLE
GCP Cloud Function deploy fails due to folder

### ISSUE THREAD

**Issue by dplessas** [schmmd/gcp-auto-tag#1]
While attempting to follow the instructions on the README, the cloud function deploy will fail with the following error message: 

```
Build failed: missing main.py and GOOGLE_FUNCTION_SOURCE not specified. Either create the function in main.py or specify GOOGLE_FUNCTION_SOURCE to point to the file that contains the function; Error ID: 5c04ec9c
```

This is due to the zip file putting everything under. the 'gcp-auto-tag-main' folder in the zip file. If you compare what is deployed with this zip here: 

![image](https://user-images.githubusercontent.com/1018123/207425955-c774bc9b-5928-4f63-b11e-fd16b4c956dc.png)

vs what is in the AllenNLP project, you will see that main.py is nested in the folder from the zip where as in AllenNLP it is a top level entry 

![image](https://user-images.githubusercontent.com/1018123/207426180-80058957-413b-42bf-bf74-f0b2b8dcf354.png)

Moving the main.py and requirements.txt to the top level allowed the function to successfully deploy. I believe we need to rebuild this zip

**Comment by dplessas** [comment]
Confirmed that this zip file works sucessfully. Created with the -D flag 
[autotagger.zip](https://github.com/schmmd/gcp-auto-tag/files/10221512/autotagger.zip)

**Comment by schmmd** [comment]
PRs welcome :-)

**Comment by dplessas** [comment]
Here is the PR for it
https://github.com/schmmd/gcp-auto-tag/pull/2
